### ISSUE TITLE
License is not mentioned

### ISSUE THREAD

**Issue by casperbakker** [PrintNode/PrintNode-PHP#2]
There is no license mentioned in the library, so it is unclear how this code may be used.

Since there is nothing special about this library, I would suggest MIT license.

It is important to mention how this code is licensed, so it can be safely used in other apps.

**Comment by PrintNodeJames** [comment]
I agree. It's now MIT licensed, 

Fixed 2cbb254837731fae3d56564ab615de5f44ed24d0

**Comment by PrintNodeJames** [comment]
I agree. It's now MIT licensed, 

Fixed 2cbb254837731fae3d56564ab615de5f44ed24d0

**Comment by casperbakker** [comment]
:+1:
