### ISSUE TITLE
Printnode Timeout

### ISSUE THREAD

**Issue by dhakalsuresh** [PrintNode/PrintNode-PHP#28]
https://github.com/PrintNode/PrintNode-PHP/blob/960acabca3c0d976bbd92bf0d6490a1fe5df7496/src/PrintNode/Request.php#L187

Error message
```RuntimeException: Uncaught exception 'RuntimeException' with message 'cURL Error (28): Operation timed out after 4000 milliseconds with 0 bytes received' in /var/www/html/vendor/printnode/printnode-php/src/PrintNode/Request.php:205```

**Comment by Fabfab67** [comment]
Hey !
Got the same type of error, any chance you solved it ?

Thanks

**Comment by votala** [comment]
Having the same issue here. i setted timeout to 10 seconds but still same problem. contacted servicedesk but they replied that they have no issue on their side. printnode is loosing one more client if this curl issue is not solved soon

**Comment by dhakalsuresh** [comment]
it was fixed in https://github.com/PrintNode/PrintNode-PHP/blob/master/src/PrintNode/Request.php#L317
