### ISSUE TITLE
Library no longer works with PHP7.4

### ISSUE THREAD

**Issue by timramakers** [PrintNode/PrintNode-PHP#48]
The 'mixed' pseudotype is used in the last commit, seemingly added for PHP8 compatibility. This is not available in PHP7.4 and throws a fatal error.

This caused all of our client's applications to break. Therefore, we are moving away from this PHP library since it's not reliable.

To improve in the future:
- please create releases so we users have control over which version we are using. Using dev-master in composer.json is not acceptable for any kind of production environment;
- please test in all supported versions of PHP before putting out a new release.

**Comment by DjThossi** [comment]
I agree the last commit was not a good idea in master branch. The Person pushed up the PHP version in composer.json to 7 and used PHP 8 features in the same commit. This breaks the whole idea of the composer.json.

**Comment by Izet0004** [comment]
If anyone want's a quick fix

Edit line 105 inside Entity.php to expect a array

This should not be taken as a permanent fix

**Comment by cesar1983** [comment]
The problem with this library is that they don´t release versions. You must start releasing versions to avoid this situation.

**Comment by DjThossi** [comment]
Please tag branch dev-release/2.0.0 with tag 2.0.0 this will solve our problems. @PrintNodeLtd PLEASE!!!!
